export const ROUTE_NAME = {
  BASE: "/",
  HOME: "/",
  SIGNUP: "/signup",
  PROFILE: "/profile",

  // user routes
  ABOUT: "/about",
  CONTACT: "/contact",
  SERVICES: "/services",

  // admin rotes
  CATEOGRIES_TOTAL: "/cateogries-total",
  CATEOGRIES_REQUEST: "/cateogries-request",
};

export const ROUTE_DEFINATION = {
  BASE: ROUTE_NAME.HOME,
  HOME: ROUTE_NAME.HOME,
  ABOUT: ROUTE_NAME.ABOUT,
  SIGNUP: ROUTE_NAME.SIGNUP,
  CONTACT: ROUTE_NAME.CONTACT,
  SERVICES: ROUTE_NAME.SERVICES,
  PROFILE: ROUTE_NAME.PROFILE,
  CATEOGRIES_TOTAL:ROUTE_NAME.CATEOGRIES_TOTAL,
  CATEOGRIES_REQUEST:ROUTE_NAME.CATEOGRIES_REQUEST,



};
