export const ROUTE_NAME={
  BASE:"/",
  LOGIN:"/login",
  HOME:"/home",
  ABOUT:"/about"
}


export const ROUTE_DEFINATION={
BASE:ROUTE_NAME.BASE,
LOGIN:ROUTE_NAME.LOGIN,
HOME:ROUTE_NAME.HOME,
ABOUT:ROUTE_NAME.ABOUT,

}